### ISSUE TITLE
Get an idea of FFMPEG and handle the storage

### ISSUE THREAD

**Issue by vipinpaul** [BiblioNexus-Foundation/scribe#7]
> Search for a better FFMPEG package to record the audio with the properties below.

```
Sample Rate: 48000 Hz
bit rate: 24
Channel: Mono
Format: Wav 
```

**Comment by AnuMonachan** [comment]
- [ ] Set up FFmpeg in Theia environment  (ET - 7 hours)
- [ ] Create a basic FFmpeg audio recording function  (ET - 6 hours)
- [ ] Handle storage access for audio recorded using FFmpeg  (ET - 7 hours)
- [ ] Create a function to stop recording  (ET - 6 hours)
- [ ] Add pause and resume functionality  (ET - 6 hours)
- [ ] Implement logic to handle multiple takes  (ET - 7 hours)
- [ ] Develop backend API for recording controls  (ET - 7 hours)
- [ ] Check functions  (ET - 6 hours)
